### PR TITLE
Send on create confirmation email after commit

### LINKED ISSUE #4062: Asynchronous email job cannot find user
I get an exception of 
`ActiveJob::DeserializationError:  Error while trying to deserialize arguments: Couldn't find User with 'id'=xxx` while trying to follow the README to let the devise send email asynchronously. 
https://github.com/plataformatec/devise#activejob-integration

I think this is because `send_on_create_confirmation_instructions` is called `after_create`, and emails are sent before user is persisted.

### PR DESCRIPTION
**Pull request by allenwq**
Fix #4062 

Call `send_on_create_confirmation_instructions` in `after_commit` instead of `after_create`, I think this is no harm in general and it makes things like async job work.

### CODE REVIEW

**Comment by allenwq** [comment]
Got one spec failure and it passed on my  local,  have no idea > <
```
1) Failure:
ReconfirmableTest#test_should_not_require_reconfirmation_after_creating_a_record_with_#save_called_in_callback [/home/travis/build/plataformatec/devise/test/models/confirmable_test.rb:509]:
Failed assertion, no message given.
```

**Comment by allenwq** [comment]
All works now, @josevalim @lucasmazza  any comments ? Thanks !

File: Gemfile [hunk 1]
```diff
@@ -12,6 +12,7 @@ group :test do
   gem "omniauth-openid", "~> 1.0.1"
   gem "webrat", "0.7.3", require: false
   gem "mocha", "~> 1.1", require: false
+  gem 'test_after_commit', require: false
```
Comment (ulissesalmeida) [inline Gemfile]: Do we really need this gem? Can we avoid to add this dependency?

File: lib/devise/models/confirmable.rb [hunk 2]
```diff
@@ -169,7 +175,6 @@ def skip_reconfirmation!
         # in models to map to a nice sign up e-mail.
         def send_on_create_confirmation_instructions
           send_confirmation_instructions
-          skip_reconfirmation!
```
Comment (ulissesalmeida) [inline lib/devise/models/confirmable.rb]: I'm not sure if we can remove this line. It was introduced in this PR https://github.com/plataformatec/devise/pull/4043/files

**Comment by ulissesalmeida** [comment]
@allenwq Thank you for your PR. I think it would be good to add some spec that mimics that problem you have mentioned, this way avoids regressions in the future. If I get some idea on how to do it, I let you know.

File: Gemfile (hunk 1 above)
Comment (allenwq) [inline Gemfile]: There are two ways of avoiding using this gem I can think of now:

1. Manually patch AR to support transnational fixtures and callbacks, which is pretty much the gem does, but we can remove the dependency.
2. Disable transactional fixtures, this is the cleanest way I think, but need a lot of work because the records are not deleted after each spec and they will affect each other.

@ulissesalmeida What do you think, which one do you prefer ?

File: lib/devise/models/confirmable.rb (hunk 2 above)
Comment (allenwq) [inline lib/devise/models/confirmable.rb]: Thanks for the reference ! I didn't remove that line because one spec will fail. Instead I moved it above.

**Comment by allenwq** [comment]
@ulissesalmeida Yes I will add a spec to this.

File: lib/devise/models/confirmable.rb (hunk 2 above)
Comment (ulissesalmeida) [inline lib/devise/models/confirmable.rb]: Sorry, now I see, you've moved to a callback.

File: Gemfile (hunk 1 above)
Comment (ulissesalmeida) [inline Gemfile]: @allenwq I think we could use a third option, that is:

3. On Rails 5 the after commits callbacks will run. Today the Rails solve the fixtures tests using the `uses_transaction`method. We can see how they use in the PR that supports the after commits: https://github.com/rails/rails/pull/18458/files#diff-f51660d918ba5921aaae392122026533L1310

I never used this before, but I think it worth the try. What do you think?

Comment (allenwq) [inline Gemfile]: Seems I have tried this before, didn't manage to succeed. I will look into it again and get back to you. Thanks !

File: test/integration/registerable_test.rb [hunk 3]
```diff
@@ -1,6 +1,8 @@
 require 'test_helper'
 
 class RegistrationTest < Devise::IntegrationTest
+  uses_transaction :test_a_guest_user_should_receive_the_confirmation_instructions_from_the_default_mailer
```
Comment (allenwq) [inline test/integration/registerable_test.rb]: @ulissesalmeida It does not work very well, declare `uses_transaction` on one spec will break other specs, see travis build results.  I think AR just disables the transactional fixtures when you say `uses_transaction`...

Comment (ulissesalmeida) [inline test/integration/registerable_test.rb]: @allenwq You're right. I agree. Maybe the option of using the gem is better.

I think we can at least, can not use the gem configuration if we are on Rails 5 and see what happens.

You can chan the Rails 5 using a code like this: https://github.com/plataformatec/devise/blob/69bee06ceee6280b54304928bb6e55c5064abad8/test/rails_app/app/controllers/home_controller.rb#L23

Then, we can let a "TODO" to remove the gem and code when we stop to support versions below than Rails 5.

Comment (allenwq) [inline test/integration/registerable_test.rb]: Yes, my initial commit doesn't uses the gem for rails 5 :-)  and everything passed.

**Comment by allenwq** [comment]
@ulissesalmeida I reverted those changes, now using the gem and it's only applied to rails 4. Working on a spec for this.

**Comment by ulissesalmeida** [comment]
@allenwq Thanks! It's looking good! ✨

**Comment by ulissesalmeida** [comment]
@allenwq I know test a race condition is not a easy task. I think ti worth a release and we can add regression test later.

**Comment by allenwq** [comment]
Thanks ! Sorry I am on leave these days, will update the tests in a
separate PR.

**Comment by allenwq** [comment]
@ulissesalmeida Sorry I cannot get the race condition test work > < but in our production app after this commit all tests passed, there are lot of random failures before.
