### PR TITLE
Fix extented remember me

### LINKED ISSUE #3994: Extending remember me expiration enabled by default.
This commit c92996646aba2d25b2c3e235fe0c4f1a84b70d24 unwillingly enabled extending the remember me period for our application. (Devise 3.5.6)

I added this to our models to disable the behaviour:
```
private :extend_remember_period=
```

and removed (which was the default value for this config):
```
config.extend_remember_period = false
```

What would be the best way to do this in a way that will be the supported in future versions?

### PR DESCRIPTION
**Pull request by ulissesalmeida**
Now the config `extend_remember_period` is used to:

`true` - Every time the user cookie is authenticated, the
cookie expiration is updated.
`false` - Does not update the cookie expiration when the cookie is authenticated.

Closes #3994

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
:shipit:

File: test/integration/rememberable_test.rb [hunk 1]
```diff
@@ -120,6 +120,40 @@ def cookie_expires(key)
...
+
+      travel_to 1.day.ago do
+        get root_path
+        old_remember_token = request.cookies['remember_user_token']
+      end
+
+      get root_path
+      current_remember_token = request.cookies['remember_user_token']
+
+      refute_equal old_remember_token, current_remember_token
```
Comment (ulissesalmeida) [inline test/integration/rememberable_test.rb]: @josevalim My assertion was the cookie contents changing.

I could be more assertive checking the expiration keys, but the cookie is encrypted.

Worth decrypt and check the key? How I can do it?

File: lib/devise/models/rememberable.rb [hunk 2]
```diff
@@ -66,6 +66,10 @@ def remember_expires_at
         self.class.remember_for.from_now
       end
 
+      def extend_remember_period
```
Comment (lucasmazza) [inline lib/devise/models/rememberable.rb]: If we remove this method, does the metaprogramming chain that backs these configs will work like the others or we need this delegation for this case?

File: test/integration/rememberable_test.rb (hunk 1 above)
Comment (josevalim) [inline test/integration/rememberable_test.rb]: changing is fine i would say

**Comment by ulissesalmeida** [comment]
@josevalim Before I ship it, this [test](https://github.com/plataformatec/devise/blob/master/test/integration/rememberable_test.rb#L91) started to fail :(

Since we are not updating the cookie, what is the expected behavior of this feature?

File: lib/devise/models/rememberable.rb (hunk 2 above)
Comment (ulissesalmeida) [inline lib/devise/models/rememberable.rb]: @lucasmazza Need a delegation for this case. Because that configurations methods generations are included on the "ClassMethods" of the module. The the instance objects does not have access.

**Comment by lucasmazza** [comment]
:shipit:

**Comment by ulissesalmeida** [comment]
@josevalim @lucasmazza Giving you more context:

That [test](https://github.com/plataformatec/devise/blob/master/test/integration/rememberable_test.rb#L91) is [failing](https://travis-ci.org/plataformatec/devise/jobs/123186522#L343) because before the cookie was always being updated. Now the default behavior is not updated anymore.

That test was checking if user authentication with remembering token.

I think this assertion does make sense anymore. Because we are not setting cookie. My suggestion is remove this assertion:
```ruby
    assert_match /remember_user_token[^\n]*HttpOnly/, response.headers["Set-Cookie"], "Expected Set-Cookie header in response to set HttpOnly flag on remember_user_token cookie."

```

**Comment by josevalim** [comment]
@ulissesalmeida I believe you are right, we can change the test. We should probably double check in an actual application to make sure we are not breaking remember me.
