### PR TITLE
fix #3958 adding helper test to report bugs

### LINKED ISSUE #3958: Executable test script to help with devise issues
Hey Guys,

When fixing a issue on rails, I saw the rails guys has a nice executable script to share the tests/impressions (when open a new issue for example).

I created a new one for devise, please let me know if is it good for you guys, and if you guys wanna I open a PR about the contributing guide (specifying to before open a new issue try reproduce the behavior at executable test script)

ps: I know it has a little trick with test and controller, I'm trying to understand why.

[https://gist.github.com/leonardoprg/a6be19c70bd9fd032d10](https://gist.github.com/leonardoprg/a6be19c70bd9fd032d10)

just run ruby test.rb

Regards,

### PR DESCRIPTION
**Pull request by leonardoprg**
Hello guys,

as related on #3958 , this PR add to project, a executable test script to help with devise issues,

I added it to guides folder (rails uses this structure) please let me know if you guys wanna I change it.

Also, I saw you guys has the steps to report a bug on wiki,  let me know if should I update it as well (I think after the accept PR)

also, as suggests @ulissesalmeida I did changes on script, instead uses `ActionController::TestCase`, now it's using `ActionDispatch::IntegrationTest`.

Thanks,

### CODE REVIEW

File: guides/bug_report_templates/integration_test_master.rb [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+  gem 'byebug'
+end
+
+require 'rack/test'
+require 'action_controller/railtie'
+require 'active_record'
+require 'devise/rails/routes'
+require 'devise/rails/warden_compat'
+
+ActiveRecord::Base.establish_connection( adapter: :sqlite3, database:  "test.sqlite")
```
Comment (lucasmazza) [inline guides/bug_report_templates/integration_test_master.rb]: can we use the in memory database instead, like the AR templates does? This way we don't to worry about the table already existing like on line 28.

**Comment by lucasmazza** [comment]
This is promising ❤️

**Comment by leonardoprg** [comment]
@lucasmazza changed to use database in memory.

Thanks,
