### PR TITLE
Fix rails_51_and_up? method for Rails 6.rc1

### LINKED ISSUE #5070: Incorrect redirect URL in Rails 6rc1
## Pre-check

I'm trying to run my existing app with Rails 6 RC1. And I found that in specs I'm receiving a strange redirect url. I'm using I18n also, and defaults option for locale. I see that locale is included in URL 2 times.

## Environment

- Ruby 2.6
- Rails 6.0.0.RC1
- Devise "master" and 4.6.2

## Current behavior

This is failed test:

```
  1) Account::CategoriesController Unauthorized GET #index returns http redirect
     Failure/Error: expect(response).to redirect_to(new_user_session_path)
     
       Expected response to be a redirect to <http://test.host/uk/users/sign_in> but was a redirect to <http://test.host/uk/uk/users/sign_in>.
       Expected "http://test.host/uk/users/sign_in" to be === "http://test.host/uk/uk/users/sign_in".
     # ./spec/controllers/account/categories_controller_spec.rb:20:in `block (4 levels) in <top (required)>'
```

With Rails 5.2 everything was fine.

## Expected behavior

I was checking where do I've this redirect and I found in devise one thing:

```
    def rails_51_and_up?
      Rails::VERSION::MAJOR >= 5 && Rails::VERSION::MINOR >= 1
    end
```

returns "false" when I'm using Rails 6rc1. Same situation for master and latest stable versions of devise.

So I've changed the code in this PR: https://github.com/plataformatec/devise/pull/5069

And now my specs are passed.

### PR DESCRIPTION
**Pull request by igorkasyanchuk**
Fixes #5070

### CODE REVIEW

File: lib/devise/failure_app.rb [hunk 1]
```diff
@@ -279,7 +279,7 @@ def root_path_defined?(context)
     end
 
     def rails_51_and_up?
-      Rails::VERSION::MAJOR >= 5 && Rails::VERSION::MINOR >= 1
+      Rails::VERSION::MAJOR >= 6 || (Rails::VERSION::MAJOR >= 5 && Rails::VERSION::MINOR >= 1)
```
Comment (mracos) [inline lib/devise/failure_app.rb]: WDYT of using the `Gem::Version` comparator like we are doing [here](https://github.com/plataformatec/devise/blob/e3a00b27d19ba995891d7dd92394fe2900a789c2/lib/devise.rb#L305)?
So it would be something like this:
```ruby
Rails.gem_version >= Gem::Version.new("5.1")
```

Comment (igorkasyanchuk) [reply lib/devise/failure_app.rb]: Fixed, thanks!

**Comment by igorkasyanchuk** [comment]
@mracos your suggestion was applied. ready for merge

**Comment by mracos** [comment]
@igorkasyanchuk Can you rebase with master, please?

**Comment by igorkasyanchuk** [comment]
@mracos  Is it really needed, looks like a branch doesn't have any conflicts. You can do it during merge: https://help.github.com/assets/images/help/pull_requests/select-squash-and-merge-from-drop-down-menu.png

**Comment by mracos** [comment]
Thanks 💙
